#requires -Version 7.4
param([Parameter(Mandatory)][ValidateSet('Run','Capture','Review')][string]$Action,[Parameter(Mandatory)][string]$Path,[Parameter(Mandatory)][string]$Worktree,[ValidateSet('dependencies','generated','test-success','test-failure','backup-duplicate','release-evidence','recovery')][string]$Kind='generated',[ValidateSet('ephemeral','hold')][string]$Retention='hold',[string[]]$Inputs=@(),[string]$Executable,[string[]]$CommandArguments=@(),[string]$RecoveryPath,[string]$Reason,[string]$Root='',[string]$Policy,[string]$State,[switch]$DryRun)
$ErrorActionPreference='Stop';Import-Module "$PSScriptRoot/lib/disk-governance.psm1"
$c=Get-QuestContext $Root $Policy $State;$lock=Enter-QuestLock $c
try{
 $owner=Get-QuestPath $Worktree;$path=Get-QuestPath $Path;$registration=Get-QuestRegistration $c;if($owner -notin $registration.path){throw 'Unknown worktree owner'}
 Assert-QuestLocal $path $owner;if($path -eq $owner -or (Test-QuestSensitive $c $path $owner)){throw 'Protected output path'}
 $registry=Get-QuestRegistry $c;$id=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($path.ToLowerInvariant()))).ToLowerInvariant()
 if($Action -eq 'Review'){if(-not $Reason -or -not $registry.artifacts[$id]){throw 'Existing diagnostic and review reason required'};if(-not $DryRun){$registry.artifacts[$id].reviewed=$true;$registry.artifacts[$id].reviewReason=$Reason;if($registry.artifacts[$id].kind -eq 'test-failure'){$registry.artifacts[$id].retention=$Retention};Save-QuestRegistry $c $registry};return}
 $relative=[IO.Path]::GetRelativePath($owner,$path).Replace('\','/');if(Invoke-QuestGit $owner @('ls-files','--',$relative)){throw 'Tracked output cannot be registered for deletion'}
 if(-not (Invoke-QuestGit $owner @('check-ignore','--no-index',"$relative/"))){throw 'Use a dedicated ignored output; never hide existing release evidence globally'}
 if($Kind -eq 'dependencies'){if($path -notmatch '/node_modules$'){throw 'Dependency output must be node_modules'};$parent=[IO.Path]::GetDirectoryName($path);$Inputs=@("$parent/package.json","$parent/package-lock.json");$Executable='npm.cmd';$CommandArguments=@('ci','--cache',"$($c.state)/npm-cache")}
 if($Retention -eq 'ephemeral' -and $Kind -in @('release-evidence','recovery')){throw 'Release/recovery artifacts must remain held'}
 if($Retention -eq 'ephemeral' -and $Kind -ne 'backup-duplicate' -and (-not $Inputs.Count -or -not $Executable -or -not $CommandArguments.Count)){throw 'Ephemeral output requires reproducible recipe and explicit input files'}
 if($Action -eq 'Capture' -and $Retention -eq 'ephemeral' -and $Kind -ne 'backup-duplicate'){throw 'Existing content cannot be proved generated by a capture alone; retain or regenerate into an absent output using Run'}
 $materials=@();foreach($input in $Inputs){$p=Get-QuestPath $input;Assert-QuestLocal $p $owner;if($p -match '(^|/)(\.env[^/]*|credentials|signing)(/|$)|\.(db|sqlite\w*|keystore|p12|pfx|pem|key|mobileprovision)$'){throw 'Sensitive input cannot establish disposable output'};$materials+=@{path=$p;sha256=[QuestDiskNative]::Hash($p)}}
 if($DryRun){@{path=$path;kind=$Kind;retention=$Retention;recipe=@{executable=$Executable;arguments=$CommandArguments};inputs=$materials;wouldRun=($Action -eq 'Run')}|ConvertTo-Json -Depth 8;return}
 if($Action -eq 'Run'){
  if(-not $Executable){throw 'Executable required'};if(Test-Path -LiteralPath $path){throw 'Do not overwrite existing unregistered/manual output; use another new output or Capture verified provenance first'}
  $meta=$registry.worktrees[$owner.ToLowerInvariant()];if(-not $meta -or $meta.status -ne 'active'){throw 'Generated execution requires an active adopted worktree'}
  $capacity=Get-QuestAudit $c $registry;if($capacity.levels.project -eq 'Critical' -or ($Kind -eq 'dependencies' -and $capacity.levels.sharedCache -eq 'Critical') -or ($Kind -like 'test-*' -and $capacity.levels.tests -eq 'Critical') -or ($Kind -eq 'backup-duplicate' -and $capacity.levels.backups -eq 'Critical')){throw 'Capacity Critical; refuse additional generated output until proof-gated maintenance or evidence review'}
  Push-Location -LiteralPath $owner;try{& $Executable @CommandArguments;$exitCode=$LASTEXITCODE}finally{Pop-Location}
  if($exitCode){$Kind='test-failure';$Retention='hold'}
  foreach($input in $materials){if([QuestDiskNative]::Hash($input.path) -ne $input.sha256){$Retention='hold'}}
 }else{if(-not $Reason){throw 'Capture requires actual producer/provenance reason; not only a directory name'}}
 if(-not (Test-Path -LiteralPath $path)){throw 'Producer created no output at declared path'};$scan=[QuestDiskNative]::Scan($path);if($scan.Unknown.Count){throw 'Output contains cloud/reparse/unknown files'};if($scan.Directories|Where-Object {[IO.Path]::GetFileName($_) -eq '.git'}){throw 'Nested repository output'}
 $files=@();foreach($f in $scan.Files){if(Test-QuestSensitive $c $f.Path $owner){throw 'Sensitive output content; retain'};$files+=@{relative=[IO.Path]::GetRelativePath($path,$f.Path).Replace('\','/');bytes=$f.Bytes;id=$f.Id;sha256=[QuestDiskNative]::Hash($f.Path)}}
 if($Kind -eq 'backup-duplicate'){
  if(-not $RecoveryPath){throw 'Duplicate backup needs a protected recovery copy'};$recovery=Get-QuestPath $RecoveryPath;if((Test-QuestInside $recovery $path) -or (Test-QuestInside $path $recovery)){throw 'Recovery copies cannot overlap'}
  $protected=$false;foreach($p in $c.policy.protectedPaths){$anchor=if([IO.Path]::IsPathRooted($p)){$p}else{Join-Path $c.root $p};if(Test-QuestInside $recovery $anchor){$protected=$true}};if(-not $protected){throw 'Recovery anchor must be explicitly protected'}
  Assert-QuestLocal $recovery $recovery;$r=[QuestDiskNative]::Scan($recovery);if($r.Unknown.Count -or $r.Files.Count -ne $files.Count){throw 'Recovery copy count/scan mismatch'};foreach($f in $files){$target=if($f.relative -eq '.'){$recovery}else{Join-Path $recovery $f.relative};if([QuestDiskNative]::Hash($target) -ne $f.sha256){throw 'Recovery bytes differ'}};$RecoveryPath=$recovery
 }
 $registry.artifacts[$id]=@{path=$path;relative=$relative;owner=$owner;kind=$Kind;retention=$Retention;created=[DateTime]::UtcNow.ToString('o');recipe=@{executable=$Executable;arguments=$CommandArguments};inputs=$materials;files=$files;reviewed=$false;recoveryPath=$RecoveryPath;provenance=$Reason;sourceHead=(Invoke-QuestGit $owner @('rev-parse','HEAD'))}
 Save-QuestRegistry $c $registry;@{id=$id;path=$path;kind=$Kind;retention=$Retention;fileCount=$files.Count;space=(Get-QuestSpace $scan.Files)}|ConvertTo-Json -Depth 8
 if($Action -eq 'Run' -and $exitCode){throw "Producer failed ($exitCode); diagnostics held"}
}finally{Exit-QuestLock $lock}
